services:
  builder:
    image: maven:3.9.6-eclipse-temurin-17-alpine
    volumes:
      - .:/app
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    command: mvn clean package -DskipTests
  postgres-vector:
    image: ankane/pgvector:latest
    container_name: postgres-vector
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=vector_db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    network_mode: host
    volumes:
      - .data/postgresql/data:/var/lib/postgresql/data
  askfluence:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: askfluence
    ports:
      - "8088:8088"
    environment:
      - CONFLUENCE_USER_ID=pravin.nimodiya@ideas.com
      - CONFLUENCE_USER_TOKEN=dummy
      - CONFLUENCE_URL=https://ideasinc.atlassian.net/wiki/rest/api/content/
      - AWS_REGION=us-east-2
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/vector_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - AWS_USE_IAM_ROLE=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - postgres-vector
    network_mode: host

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: askfluence-frontend
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - askfluence
    working_dir: /app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    network_mode: host